### ISSUE TITLE
Goldbach's other conjecture

### ISSUE THREAD

**Issue by lparolari** [lparolari/high-school-assignments#7]
Refer to [Problem 46](https://projecteuler.net/problem=46) from Project Euler.

# Todo

- [ ] solve the problem
- [ ] add the exercise descritpion
- [ ] add entry in readme table

**Comment by lparolari** [comment]
Refer to [Problem 46](https://projecteuler.net/problem=46) from Project Euler.

Todo
[ ] solve the problem
[ ] add the exercise descritpion
[ ] add entry in readme table

**Comment by lparolari** [comment]
Text is already translated to italian. See [README.txt](https://github.com/lparolari/high-school-assignments/files/6093684/README.txt).
