### ISSUE TITLE
Perfect Square Collection

### ISSUE THREAD

**Issue by lparolari** [lparolari/high-school-assignments#8]
Refer to [Problem 142](https://projecteuler.net/problem=142) from Project Euler.

# Todo

- [ ] solve the problem
- [ ] add the exercise descritpion
- [ ] add entry in readme table

The problem is already translated to italian. See [README.txt](https://github.com/lparolari/high-school-assignments/files/6093707/README.txt).
