### ISSUE TITLE
Dynamic Polymorphism

### ISSUE THREAD

**Issue by lparolari** [lparolari/high-school-assignments#9]
I've found this [awesome collection of (solved) exercises](https://www.ece.iastate.edu/~alexs/classes/2007_Fall_207/lab_manual/chapter9_lab.pdf) on dynamic polymorphism. There are plenty of good examples on how polymorphism works and why is useful, not only the same old example on "geometric shapes".

## Todo

* [ ] select and/or simplify exercises from the collection
* [ ] translate the text and, if required, also the code
* [ ] write the assigment
* [ ] cite the author

## Attachments
* [Alex Stoytchev's classes homepage](https://www.ece.iastate.edu/~alexs/classes/)
* [Exercises collection (pdf)](https://github.com/lparolari/high-school-assignments/files/6195821/chapter9_lab.pdf)
